"""""
Author: Roufiel Hadi
NIM: 241524028
Kelas: 1A
Prodi: Sarjana Terapan Teknik Informatika
Jurusan: Teknik Komputer dan Informatika
Politeknik Negeri Bandung
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_rekening.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard_rekening_sakapeung(object):
    def setupUi(self, dashboard_rekening_sakapeung):
        dashboard_rekening_sakapeung.setObjectName("dashboard_rekening_sakapeung")
        dashboard_rekening_sakapeung.resize(1107, 879)
        dashboard_rekening_sakapeung.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(dashboard_rekening_sakapeung)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_utama)
        self.stackedWidget.setGeometry(QtCore.QRect(240, 0, 811, 781))
        self.stackedWidget.setStyleSheet("background : white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.rekening = QtWidgets.QWidget()
        self.rekening.setObjectName("rekening")
        self.home_rekening = QtWidgets.QTextEdit(self.rekening)
        self.home_rekening.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.home_rekening.setObjectName("home_rekening")
        self.home_title_rekening = QtWidgets.QTextBrowser(self.rekening)
        self.home_title_rekening.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_rekening.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_rekening.setObjectName("home_title_rekening")
        self.stackedWidget.addWidget(self.rekening)
        self.lihat_informasi_rekening = QtWidgets.QWidget()
        self.lihat_informasi_rekening.setObjectName("lihat_informasi_rekening")
        self.lihat_informasi_rekening_tittle_rekening = QtWidgets.QTextBrowser(self.lihat_informasi_rekening)
        self.lihat_informasi_rekening_tittle_rekening.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.lihat_informasi_rekening_tittle_rekening.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.lihat_informasi_rekening_tittle_rekening.setObjectName("lihat_informasi_rekening_tittle_rekening")
        self.lihat_informasi_rekening_rekening = QtWidgets.QTextEdit(self.lihat_informasi_rekening)
        self.lihat_informasi_rekening_rekening.setGeometry(QtCore.QRect(10, 280, 791, 491))
        self.lihat_informasi_rekening_rekening.setObjectName("lihat_informasi_rekening_rekening")
        self.pin_konfirmasi_LIR_input = QtWidgets.QLineEdit(self.lihat_informasi_rekening)
        self.pin_konfirmasi_LIR_input.setGeometry(QtCore.QRect(30, 130, 731, 61))
        self.pin_konfirmasi_LIR_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.pin_konfirmasi_LIR_input.setText("")
        self.pin_konfirmasi_LIR_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin_konfirmasi_LIR_input.setObjectName("pin_konfirmasi_LIR_input")
        self.submit_pin_LIR = QtWidgets.QPushButton(self.lihat_informasi_rekening)
        self.submit_pin_LIR.setGeometry(QtCore.QRect(270, 220, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit_pin_LIR.setFont(font)
        self.submit_pin_LIR.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.submit_pin_LIR.setObjectName("submit_pin_LIR")
        self.stackedWidget.addWidget(self.lihat_informasi_rekening)
        self.edit_informasi_rekening = QtWidgets.QWidget()
        self.edit_informasi_rekening.setObjectName("edit_informasi_rekening")
        self.edit_informasi_rekening_tittle_rekening = QtWidgets.QTextBrowser(self.edit_informasi_rekening)
        self.edit_informasi_rekening_tittle_rekening.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.edit_informasi_rekening_tittle_rekening.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.edit_informasi_rekening_tittle_rekening.setObjectName("edit_informasi_rekening_tittle_rekening")
        self.pin_konfirmasi_no_rekening_input = QtWidgets.QLineEdit(self.edit_informasi_rekening)
        self.pin_konfirmasi_no_rekening_input.setGeometry(QtCore.QRect(30, 150, 731, 61))
        self.pin_konfirmasi_no_rekening_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.pin_konfirmasi_no_rekening_input.setText("")
        self.pin_konfirmasi_no_rekening_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin_konfirmasi_no_rekening_input.setObjectName("pin_konfirmasi_no_rekening_input")
        self.submit_ganti_nomor_rekening = QtWidgets.QPushButton(self.edit_informasi_rekening)
        self.submit_ganti_nomor_rekening.setGeometry(QtCore.QRect(270, 320, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit_ganti_nomor_rekening.setFont(font)
        self.submit_ganti_nomor_rekening.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.submit_ganti_nomor_rekening.setObjectName("submit_ganti_nomor_rekening")
        self.nomor_rekening_baru_input = QtWidgets.QLineEdit(self.edit_informasi_rekening)
        self.nomor_rekening_baru_input.setGeometry(QtCore.QRect(30, 220, 731, 61))
        self.nomor_rekening_baru_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.nomor_rekening_baru_input.setText("")
        self.nomor_rekening_baru_input.setObjectName("nomor_rekening_baru_input")
        self.pin_baru_input = QtWidgets.QLineEdit(self.edit_informasi_rekening)
        self.pin_baru_input.setGeometry(QtCore.QRect(30, 470, 731, 61))
        self.pin_baru_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.pin_baru_input.setText("")
        self.pin_baru_input.setObjectName("pin_baru_input")
        self.konfirmasi_pin_baru_input = QtWidgets.QLineEdit(self.edit_informasi_rekening)
        self.konfirmasi_pin_baru_input.setGeometry(QtCore.QRect(30, 530, 731, 61))
        self.konfirmasi_pin_baru_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.konfirmasi_pin_baru_input.setText("")
        self.konfirmasi_pin_baru_input.setObjectName("konfirmasi_pin_baru_input")
        self.pin_konfirmasi_pin_input = QtWidgets.QLineEdit(self.edit_informasi_rekening)
        self.pin_konfirmasi_pin_input.setGeometry(QtCore.QRect(30, 410, 731, 61))
        self.pin_konfirmasi_pin_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.pin_konfirmasi_pin_input.setText("")
        self.pin_konfirmasi_pin_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin_konfirmasi_pin_input.setObjectName("pin_konfirmasi_pin_input")
        self.submit_ganti_pin = QtWidgets.QPushButton(self.edit_informasi_rekening)
        self.submit_ganti_pin.setGeometry(QtCore.QRect(270, 610, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit_ganti_pin.setFont(font)
        self.submit_ganti_pin.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.submit_ganti_pin.setObjectName("submit_ganti_pin")
        self.stackedWidget.addWidget(self.edit_informasi_rekening)
        self.top_up = QtWidgets.QWidget()
        self.top_up.setObjectName("top_up")
        self.top_up_title_rekening = QtWidgets.QTextBrowser(self.top_up)
        self.top_up_title_rekening.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.top_up_title_rekening.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.top_up_title_rekening.setObjectName("top_up_title_rekening")
        self.pin_konfirmasi_TU_input = QtWidgets.QLineEdit(self.top_up)
        self.pin_konfirmasi_TU_input.setGeometry(QtCore.QRect(40, 140, 731, 61))
        self.pin_konfirmasi_TU_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.pin_konfirmasi_TU_input.setText("")
        self.pin_konfirmasi_TU_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin_konfirmasi_TU_input.setObjectName("pin_konfirmasi_TU_input")
        self.submit_saldo_topup = QtWidgets.QPushButton(self.top_up)
        self.submit_saldo_topup.setGeometry(QtCore.QRect(280, 340, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit_saldo_topup.setFont(font)
        self.submit_saldo_topup.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.submit_saldo_topup.setObjectName("submit_saldo_topup")
        self.Saldo_topup_input = QtWidgets.QLineEdit(self.top_up)
        self.Saldo_topup_input.setGeometry(QtCore.QRect(40, 220, 731, 61))
        self.Saldo_topup_input.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.Saldo_topup_input.setText("")
        self.Saldo_topup_input.setObjectName("Saldo_topup_input")
        self.stackedWidget.addWidget(self.top_up)
        self.home_button = QtWidgets.QPushButton(self.frame_utama)
        self.home_button.setGeometry(QtCore.QRect(10, 210, 221, 81))
        self.home_button.setMouseTracking(True)
        self.home_button.setTabletTracking(True)
        self.home_button.setObjectName("home_button")
        self.sakapeung = QtWidgets.QTextBrowser(self.frame_utama)
        self.sakapeung.setGeometry(QtCore.QRect(10, 30, 251, 71))
        self.sakapeung.setStyleSheet("  background: transparent;")
        self.sakapeung.setObjectName("sakapeung")
        self.lihat_informasi_rekening_button = QtWidgets.QPushButton(self.frame_utama)
        self.lihat_informasi_rekening_button.setGeometry(QtCore.QRect(10, 300, 221, 81))
        self.lihat_informasi_rekening_button.setMouseTracking(True)
        self.lihat_informasi_rekening_button.setTabletTracking(True)
        self.lihat_informasi_rekening_button.setObjectName("lihat_informasi_rekening_button")
        self.edit_informasi_rekening_button = QtWidgets.QPushButton(self.frame_utama)
        self.edit_informasi_rekening_button.setGeometry(QtCore.QRect(10, 390, 221, 81))
        self.edit_informasi_rekening_button.setMouseTracking(True)
        self.edit_informasi_rekening_button.setTabletTracking(True)
        self.edit_informasi_rekening_button.setObjectName("edit_informasi_rekening_button")
        self.top_up_button = QtWidgets.QPushButton(self.frame_utama)
        self.top_up_button.setGeometry(QtCore.QRect(10, 480, 221, 81))
        self.top_up_button.setMouseTracking(True)
        self.top_up_button.setTabletTracking(True)
        self.top_up_button.setObjectName("top_up_button")
        self.kembali_button = QtWidgets.QPushButton(self.frame_utama)
        self.kembali_button.setGeometry(QtCore.QRect(10, 570, 221, 81))
        self.kembali_button.setMouseTracking(True)
        self.kembali_button.setTabletTracking(True)
        self.kembali_button.setObjectName("kembali_button")
        self.sakapeung.raise_()
        self.stackedWidget.raise_()
        self.home_button.raise_()
        self.lihat_informasi_rekening_button.raise_()
        self.edit_informasi_rekening_button.raise_()
        self.top_up_button.raise_()
        self.kembali_button.raise_()
        dashboard_rekening_sakapeung.setCentralWidget(self.centralwidget)

        self.retranslateUi(dashboard_rekening_sakapeung)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dashboard_rekening_sakapeung)

    def retranslateUi(self, dashboard_rekening_sakapeung):
        _translate = QtCore.QCoreApplication.translate
        dashboard_rekening_sakapeung.setWindowTitle(_translate("dashboard_rekening_sakapeung", "Dashboard SAKAPEUNG"))
        self.home_rekening.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ini adalah dashboard rekening</p></body></html>"))
        self.home_title_rekening.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Dashboard Rekening</span></p></body></html>"))
        self.lihat_informasi_rekening_tittle_rekening.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lihat Informasi Rekening</span></p></body></html>"))
        self.lihat_informasi_rekening_rekening.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pin_konfirmasi_LIR_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan pin anda....."))
        self.submit_pin_LIR.setText(_translate("dashboard_rekening_sakapeung", "Submit"))
        self.edit_informasi_rekening_tittle_rekening.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Edit Informasi Rekening</span></p></body></html>"))
        self.pin_konfirmasi_no_rekening_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan pin anda....."))
        self.submit_ganti_nomor_rekening.setText(_translate("dashboard_rekening_sakapeung", "Ganti Nomor Rekening"))
        self.nomor_rekening_baru_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan nomor rekening anda....."))
        self.pin_baru_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan pin baru anda....."))
        self.konfirmasi_pin_baru_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan ulang pin baru anda....."))
        self.pin_konfirmasi_pin_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan pin anda....."))
        self.submit_ganti_pin.setText(_translate("dashboard_rekening_sakapeung", "Ganti Pin"))
        self.top_up_title_rekening.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Top Up Saldo</span></p></body></html>"))
        self.pin_konfirmasi_TU_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan pin anda....."))
        self.submit_saldo_topup.setText(_translate("dashboard_rekening_sakapeung", "Submit"))
        self.Saldo_topup_input.setPlaceholderText(_translate("dashboard_rekening_sakapeung", "masukkan jumlah saldo yang akan di top up....."))
        self.home_button.setText(_translate("dashboard_rekening_sakapeung", "Home"))
        self.sakapeung.setHtml(_translate("dashboard_rekening_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">SAKAPEUNG</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p></body></html>"))
        self.lihat_informasi_rekening_button.setText(_translate("dashboard_rekening_sakapeung", "Lihat Informasi Rekening"))
        self.edit_informasi_rekening_button.setText(_translate("dashboard_rekening_sakapeung", "Edit Informasi Rekening"))
        self.top_up_button.setText(_translate("dashboard_rekening_sakapeung", "Top Up Saldo"))
        self.kembali_button.setText(_translate("dashboard_rekening_sakapeung", "Kembali Ke Dashboard Utama"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard_rekening_sakapeung = QtWidgets.QMainWindow()
    ui = Ui_dashboard_rekening_sakapeung()
    ui.setupUi(dashboard_rekening_sakapeung)
    dashboard_rekening_sakapeung.show()
    sys.exit(app.exec_())
