"""""
Author: Roufiel Hadi
NIM: 241524028
Kelas: 1A
Prodi: Sarjana Terapan Teknik Informatika
Jurusan: Teknik Komputer dan Informatika
Politeknik Negeri Bandung
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard_admin_sakapeung(object):
    def setupUi(self, dashboard_admin_sakapeung):
        dashboard_admin_sakapeung.setObjectName("dashboard_admin_sakapeung")
        dashboard_admin_sakapeung.resize(1107, 879)
        dashboard_admin_sakapeung.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(dashboard_admin_sakapeung)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_utama)
        self.stackedWidget.setGeometry(QtCore.QRect(240, 0, 811, 781))
        self.stackedWidget.setStyleSheet("background : white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.admin = QtWidgets.QWidget()
        self.admin.setObjectName("admin")
        self.home_admin = QtWidgets.QTextEdit(self.admin)
        self.home_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.home_admin.setObjectName("home_admin")
        self.home_title_admin = QtWidgets.QTextBrowser(self.admin)
        self.home_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_admin.setObjectName("home_title_admin")
        self.stackedWidget.addWidget(self.admin)
        self.edit_jadwal_kereta = QtWidgets.QWidget()
        self.edit_jadwal_kereta.setObjectName("edit_jadwal_kereta")
        self.edit_jadwal_kereta_title_admin = QtWidgets.QTextBrowser(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.edit_jadwal_kereta_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.edit_jadwal_kereta_title_admin.setObjectName("edit_jadwal_kereta_title_admin")
        self.edit_jadwal_kereta_admin = QtWidgets.QTextEdit(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.edit_jadwal_kereta_admin.setObjectName("edit_jadwal_kereta_admin")
        self.stackedWidget.addWidget(self.edit_jadwal_kereta)
        self.lihat_rekap_keuntungan = QtWidgets.QWidget()
        self.lihat_rekap_keuntungan.setObjectName("lihat_rekap_keuntungan")
        self.lihat_rekap_keuntungan_title_admin = QtWidgets.QTextBrowser(self.lihat_rekap_keuntungan)
        self.lihat_rekap_keuntungan_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.lihat_rekap_keuntungan_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px;\n"
"")
        self.lihat_rekap_keuntungan_title_admin.setObjectName("lihat_rekap_keuntungan_title_admin")
        self.lihat_rekap_keuntungan_admin = QtWidgets.QTextEdit(self.lihat_rekap_keuntungan)
        self.lihat_rekap_keuntungan_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.lihat_rekap_keuntungan_admin.setObjectName("lihat_rekap_keuntungan_admin")
        self.stackedWidget.addWidget(self.lihat_rekap_keuntungan)
        self.home_button = QtWidgets.QPushButton(self.frame_utama)
        self.home_button.setGeometry(QtCore.QRect(10, 210, 221, 81))
        self.home_button.setMouseTracking(True)
        self.home_button.setTabletTracking(True)
        self.home_button.setObjectName("home_button")
        self.sakapeung = QtWidgets.QTextBrowser(self.frame_utama)
        self.sakapeung.setGeometry(QtCore.QRect(10, 30, 251, 71))
        self.sakapeung.setStyleSheet("  background: transparent;")
        self.sakapeung.setObjectName("sakapeung")
        self.edit_jadwal_kereta_button = QtWidgets.QPushButton(self.frame_utama)
        self.edit_jadwal_kereta_button.setGeometry(QtCore.QRect(10, 300, 221, 81))
        self.edit_jadwal_kereta_button.setMouseTracking(True)
        self.edit_jadwal_kereta_button.setTabletTracking(True)
        self.edit_jadwal_kereta_button.setObjectName("edit_jadwal_kereta_button")
        self.lihat_rekap_keuntungan_button = QtWidgets.QPushButton(self.frame_utama)
        self.lihat_rekap_keuntungan_button.setGeometry(QtCore.QRect(10, 390, 221, 81))
        self.lihat_rekap_keuntungan_button.setMouseTracking(True)
        self.lihat_rekap_keuntungan_button.setTabletTracking(True)
        self.lihat_rekap_keuntungan_button.setObjectName("lihat_rekap_keuntungan_button")
        self.logout_button = QtWidgets.QPushButton(self.frame_utama)
        self.logout_button.setGeometry(QtCore.QRect(10, 480, 221, 81))
        self.logout_button.setMouseTracking(True)
        self.logout_button.setTabletTracking(True)
        self.logout_button.setObjectName("logout_button")
        self.keluar_button = QtWidgets.QPushButton(self.frame_utama)
        self.keluar_button.setGeometry(QtCore.QRect(10, 570, 221, 81))
        self.keluar_button.setMouseTracking(True)
        self.keluar_button.setTabletTracking(True)
        self.keluar_button.setObjectName("keluar_button")
        self.sakapeung.raise_()
        self.stackedWidget.raise_()
        self.home_button.raise_()
        self.edit_jadwal_kereta_button.raise_()
        self.lihat_rekap_keuntungan_button.raise_()
        self.logout_button.raise_()
        self.keluar_button.raise_()
        dashboard_admin_sakapeung.setCentralWidget(self.centralwidget)

        self.retranslateUi(dashboard_admin_sakapeung)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(dashboard_admin_sakapeung)

    def retranslateUi(self, dashboard_admin_sakapeung):
        _translate = QtCore.QCoreApplication.translate
        dashboard_admin_sakapeung.setWindowTitle(_translate("dashboard_admin_sakapeung", "Dashboard SAKAPEUNG"))
        self.home_admin.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ini adalah dashbiard admin</p></body></html>"))
        self.home_title_admin.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Dashboard Admin</span></p></body></html>"))
        self.edit_jadwal_kereta_title_admin.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Edit Jadwal Kereta</span></p></body></html>"))
        self.edit_jadwal_kereta_admin.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ini adalah menu edit jadwal kereta</p></body></html>"))
        self.lihat_rekap_keuntungan_title_admin.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lihat Rekap Keuntungan</span></p></body></html>"))
        self.lihat_rekap_keuntungan_admin.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ini adalah menu lihat rekap keuntungan</p></body></html>"))
        self.home_button.setText(_translate("dashboard_admin_sakapeung", "Home"))
        self.sakapeung.setHtml(_translate("dashboard_admin_sakapeung", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">SAKAPEUNG</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p></body></html>"))
        self.edit_jadwal_kereta_button.setText(_translate("dashboard_admin_sakapeung", "Edit Jadwal Kereta"))
        self.lihat_rekap_keuntungan_button.setText(_translate("dashboard_admin_sakapeung", "Lihat Rekap Keuntungan"))
        self.logout_button.setText(_translate("dashboard_admin_sakapeung", "Log Out"))
        self.keluar_button.setText(_translate("dashboard_admin_sakapeung", "Keluar Dari Aplikasi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard_admin_sakapeung = QtWidgets.QMainWindow()
    ui = Ui_dashboard_admin_sakapeung()
    ui.setupUi(dashboard_admin_sakapeung)
    dashboard_admin_sakapeung.show()
    sys.exit(app.exec_())
