# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail_RekapKeuntungan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_detail_RekapKeuntungan(object):
    def setupUi(self, detail_RekapKeuntungan):
        detail_RekapKeuntungan.setObjectName("detail_RekapKeuntungan")
        detail_RekapKeuntungan.resize(1107, 879)
        detail_RekapKeuntungan.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(detail_RekapKeuntungan)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_utama)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1051, 781))
        self.stackedWidget.setStyleSheet("background : white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.admin = QtWidgets.QWidget()
        self.admin.setObjectName("admin")
        self.home_admin = QtWidgets.QTextEdit(self.admin)
        self.home_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.home_admin.setObjectName("home_admin")
        self.home_title_admin = QtWidgets.QTextBrowser(self.admin)
        self.home_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_admin.setObjectName("home_title_admin")
        self.stackedWidget.addWidget(self.admin)
        self.edit_jadwal_kereta = QtWidgets.QWidget()
        self.edit_jadwal_kereta.setObjectName("edit_jadwal_kereta")
        self.edit_jadwal_kereta_title_admin = QtWidgets.QTextBrowser(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.edit_jadwal_kereta_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.edit_jadwal_kereta_title_admin.setObjectName("edit_jadwal_kereta_title_admin")
        self.edit_jadwal_kereta_admin = QtWidgets.QTextEdit(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.edit_jadwal_kereta_admin.setObjectName("edit_jadwal_kereta_admin")
        self.stackedWidget.addWidget(self.edit_jadwal_kereta)
        self.lihat_rekap_keuntungan = QtWidgets.QWidget()
        self.lihat_rekap_keuntungan.setObjectName("lihat_rekap_keuntungan")
        self.lihat_rekap_keuntungan_title_admin = QtWidgets.QTextBrowser(self.lihat_rekap_keuntungan)
        self.lihat_rekap_keuntungan_title_admin.setGeometry(QtCore.QRect(-10, 0, 1061, 111))
        self.lihat_rekap_keuntungan_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px;\n"
"")
        self.lihat_rekap_keuntungan_title_admin.setObjectName("lihat_rekap_keuntungan_title_admin")
        self.combo_filter_rekap = QtWidgets.QComboBox(self.lihat_rekap_keuntungan)
        self.combo_filter_rekap.setGeometry(QtCore.QRect(210, 260, 71, 31))
        self.combo_filter_rekap.setStyleSheet("#combo_filter_rekap {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: #ffffff;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 5px;\n"
"    border-radius: 6px;\n"
"    border: 2px solid #4a00e0;\n"
"    selection-background-color: #4a00e0;\n"
"}\n"
"\n"
"/* Dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #6a11cb;\n"
"    color: white;\n"
"    selection-background-color: #2575fc;\n"
"    border: 1px solid #4a00e0;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Saat hover */\n"
"#combo_filter_rekap:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #4a00e0, stop:1 #6a11cb);\n"
"}\n"
"\n"
"/* Saat ditekan */\n"
"#combo_filter_rekap:on {\n"
"    background: #4a00e0;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.combo_filter_rekap.setObjectName("combo_filter_rekap")
        self.combo_filter_rekap.addItem("")
        self.combo_filter_rekap.addItem("")
        self.combo_filter_rekap.addItem("")
        self.combo_filter_rekap.addItem("")
        self.label = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label.setGeometry(QtCore.QRect(430, 150, 191, 41))
        self.label.setStyleSheet("/* Judul \"Lihat Rekap Keuntungan\" dengan background gradasi */\n"
"QLabel#label {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 12px;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    border: 2px solid #4a00e0;\n"
"}")
        self.label.setObjectName("label")
        self.table_lihat_detail_rekap_keuntungan = QtWidgets.QTableWidget(self.lihat_rekap_keuntungan)
        self.table_lihat_detail_rekap_keuntungan.setGeometry(QtCore.QRect(310, 260, 531, 291))
        self.table_lihat_detail_rekap_keuntungan.setStyleSheet("#table_lihat_detail_rekap_keuntungan {\n"
"    background-color: #E3F2FD; /* Biru muda pastel */\n"
"    gridline-color: #BBDEFB; /* Garis antar sel */\n"
"    border: 2px solid #1976D2; /* Border biru sedang */\n"
"    font-size: 10px;\n"
"    color: #0D47A1; /* Warna teks biru tua */\n"
"    selection-background-color: #42A5F5; /* Biru lebih cerah saat dipilih */\n"
"    selection-color: white; /* Teks putih saat dipilih */\n"
"    alternate-background-color: #FFFFFF; /* Warna sel bergantian */\n"
"}\n"
"\n"
"/* Header tabel dengan gradasi */\n"
"QHeaderView::section {\n"
"    font-size: 10x;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 6px;\n"
"    border: 2px solid #4a00e0;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    border: 2px solid #4a00e0;\n"
"}\n"
"\n"
"/* Efek hover & selected */\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"/* Scrollbar Custom */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #E3F2FD;\n"
"    width: 10px;\n"
"    margin: 2px 0 2px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #1976D2;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"")
        self.table_lihat_detail_rekap_keuntungan.setObjectName("table_lihat_detail_rekap_keuntungan")
        self.table_lihat_detail_rekap_keuntungan.setColumnCount(7)
        self.table_lihat_detail_rekap_keuntungan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_detail_rekap_keuntungan.setHorizontalHeaderItem(6, item)
        self.button_kembali = QtWidgets.QPushButton(self.lihat_rekap_keuntungan)
        self.button_kembali.setGeometry(QtCore.QRect(430, 570, 91, 31))
        self.button_kembali.setStyleSheet("#button_kembali {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border: 2px solid #B71C1C;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF8A80, stop:1 #D32F2F); /* Lebih banyak merah terang */\n"
"}\n"
"\n"
"/* Efek hover */\n"
"#button_kembali:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF5252, stop:1 #B71C1C); /* Lebih merah saat hover */\n"
"    border: 2px solid #D32F2F;\n"
"}\n"
"\n"
"/* Efek tombol ditekan */\n"
"#button_kembali:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #F44336, stop:1 #9A0007); /* Merah lebih gelap saat ditekan */\n"
"    border: 2px solid #7F0000;\n"
"}\n"
"")
        self.button_kembali.setObjectName("button_kembali")
        self.label_2 = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_2.setGeometry(QtCore.QRect(310, 220, 121, 31))
        self.label_2.setStyleSheet("#label_2 {\n"
"     font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_total_pemasukan = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_total_pemasukan.setGeometry(QtCore.QRect(440, 220, 161, 31))
        self.label_total_pemasukan.setStyleSheet("#label_total_pemasukan {\n"
"     font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_total_pemasukan.setObjectName("label_total_pemasukan")
        self.button_lihat_grafik = QtWidgets.QPushButton(self.lihat_rekap_keuntungan)
        self.button_lihat_grafik.setGeometry(QtCore.QRect(320, 570, 91, 31))
        self.button_lihat_grafik.setStyleSheet("QPushButton#button_lihat_grafik {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #1976D2, stop:1 #64B5F6);\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #1565C0;\n"
"}\n"
"\n"
"/* Efek hover */\n"
"#button_lihat_grafik:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #1565C0, stop:1 #42A5F5);\n"
"}\n"
"\n"
"/* Efek tombol ditekan */\n"
"#button_lihat_grafik:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #F44336, stop:1 #9A0007); /* Merah lebih gelap saat ditekan */\n"
"    border: 2px solid #7F0000;\n"
"}\n"
"")
        self.button_lihat_grafik.setObjectName("button_lihat_grafik")
        self.stackedWidget.addWidget(self.lihat_rekap_keuntungan)
        self.sakapeung = QtWidgets.QTextBrowser(self.frame_utama)
        self.sakapeung.setGeometry(QtCore.QRect(10, 30, 251, 71))
        self.sakapeung.setStyleSheet("  background: transparent;")
        self.sakapeung.setObjectName("sakapeung")
        self.sakapeung.raise_()
        self.stackedWidget.raise_()
        detail_RekapKeuntungan.setCentralWidget(self.centralwidget)

        self.retranslateUi(detail_RekapKeuntungan)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(detail_RekapKeuntungan)

    def retranslateUi(self, detail_RekapKeuntungan):
        _translate = QtCore.QCoreApplication.translate
        detail_RekapKeuntungan.setWindowTitle(_translate("detail_RekapKeuntungan", "Dashboard SAKAPEUNG"))
        self.home_admin.setHtml(_translate("detail_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah dashbiard admin</span></p></body></html>"))
        self.home_title_admin.setHtml(_translate("detail_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Dashboard Admin</span></p></body></html>"))
        self.edit_jadwal_kereta_title_admin.setHtml(_translate("detail_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Edit Jadwal Kereta</span></p></body></html>"))
        self.edit_jadwal_kereta_admin.setHtml(_translate("detail_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu edit jadwal kereta</span></p></body></html>"))
        self.lihat_rekap_keuntungan_title_admin.setHtml(_translate("detail_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lihat Rekap Keuntungan</span></p></body></html>"))
        self.combo_filter_rekap.setItemText(0, _translate("detail_RekapKeuntungan", "Harian"))
        self.combo_filter_rekap.setItemText(1, _translate("detail_RekapKeuntungan", "Mingguan"))
        self.combo_filter_rekap.setItemText(2, _translate("detail_RekapKeuntungan", "Bulanan"))
        self.combo_filter_rekap.setItemText(3, _translate("detail_RekapKeuntungan", "Tahunan"))
        self.label.setText(_translate("detail_RekapKeuntungan", "Detail Rekap Keuntungan"))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(0)
        item.setText(_translate("detail_RekapKeuntungan", "Nama "))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(1)
        item.setText(_translate("detail_RekapKeuntungan", "Email"))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(2)
        item.setText(_translate("detail_RekapKeuntungan", "Nama Kereta"))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(3)
        item.setText(_translate("detail_RekapKeuntungan", "ID Kereta"))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(4)
        item.setText(_translate("detail_RekapKeuntungan", "ID Kursi"))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(5)
        item.setText(_translate("detail_RekapKeuntungan", "Total Tarif"))
        item = self.table_lihat_detail_rekap_keuntungan.horizontalHeaderItem(6)
        item.setText(_translate("detail_RekapKeuntungan", "Tanggal"))
        self.button_kembali.setText(_translate("detail_RekapKeuntungan", "Kembali"))
        self.label_2.setText(_translate("detail_RekapKeuntungan", "Total Pemasukan:"))
        self.label_total_pemasukan.setText(_translate("detail_RekapKeuntungan", "TextLabel"))
        self.button_lihat_grafik.setText(_translate("detail_RekapKeuntungan", "Lihat Grafik"))
        self.sakapeung.setHtml(_translate("detail_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">SAKAPEUNG</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:22pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    detail_RekapKeuntungan = QtWidgets.QMainWindow()
    ui = Ui_detail_RekapKeuntungan()
    ui.setupUi(detail_RekapKeuntungan)
    detail_RekapKeuntungan.show()
    sys.exit(app.exec_())
