# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail_tiket.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard_detail_tiket(object):
    def setupUi(self, dashboard_detail_tiket):
        dashboard_detail_tiket.setObjectName("dashboard_detail_tiket")
        dashboard_detail_tiket.resize(1107, 879)
        dashboard_detail_tiket.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(dashboard_detail_tiket)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.user = QtWidgets.QStackedWidget(self.frame_utama)
        self.user.setGeometry(QtCore.QRect(0, 0, 1051, 781))
        self.user.setStyleSheet("background : white;")
        self.user.setFrameShape(QtWidgets.QFrame.Box)
        self.user.setFrameShadow(QtWidgets.QFrame.Plain)
        self.user.setObjectName("user")
        self.user_dashboard = QtWidgets.QWidget()
        self.user_dashboard.setObjectName("user_dashboard")
        self.home_user = QtWidgets.QTextEdit(self.user_dashboard)
        self.home_user.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.home_user.setObjectName("home_user")
        self.home_title_user = QtWidgets.QTextBrowser(self.user_dashboard)
        self.home_title_user.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_user.setObjectName("home_title_user")
        self.user.addWidget(self.user_dashboard)
        self.pembelian_tiket = QtWidgets.QWidget()
        self.pembelian_tiket.setObjectName("pembelian_tiket")
        self.pembelian_tiket_title_user = QtWidgets.QTextBrowser(self.pembelian_tiket)
        self.pembelian_tiket_title_user.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.pembelian_tiket_title_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.pembelian_tiket_title_user.setObjectName("pembelian_tiket_title_user")
        self.pembelian_tiket_user = QtWidgets.QTextEdit(self.pembelian_tiket)
        self.pembelian_tiket_user.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.pembelian_tiket_user.setObjectName("pembelian_tiket_user")
        self.user.addWidget(self.pembelian_tiket)
        self.lihat_jadwal_kereta = QtWidgets.QWidget()
        self.lihat_jadwal_kereta.setObjectName("lihat_jadwal_kereta")
        self.lihat_jadwal_kereta_title_user = QtWidgets.QTextBrowser(self.lihat_jadwal_kereta)
        self.lihat_jadwal_kereta_title_user.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.lihat_jadwal_kereta_title_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; ")
        self.lihat_jadwal_kereta_title_user.setObjectName("lihat_jadwal_kereta_title_user")
        self.lihat_jadwal_kereta_user = QtWidgets.QTextEdit(self.lihat_jadwal_kereta)
        self.lihat_jadwal_kereta_user.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.lihat_jadwal_kereta_user.setObjectName("lihat_jadwal_kereta_user")
        self.user.addWidget(self.lihat_jadwal_kereta)
        self.tiket_saya = QtWidgets.QWidget()
        self.tiket_saya.setObjectName("tiket_saya")
        self.tiket_saya_tittle_user = QtWidgets.QTextBrowser(self.tiket_saya)
        self.tiket_saya_tittle_user.setGeometry(QtCore.QRect(0, 0, 1051, 111))
        self.tiket_saya_tittle_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; ")
        self.tiket_saya_tittle_user.setObjectName("tiket_saya_tittle_user")
        self.frame_detail_tiket = QtWidgets.QFrame(self.tiket_saya)
        self.frame_detail_tiket.setGeometry(QtCore.QRect(270, 190, 491, 471))
        self.frame_detail_tiket.setMinimumSize(QtCore.QSize(300, 400))
        self.frame_detail_tiket.setStyleSheet("/* Frame utama */\n"
"QFrame#frame_detail_tiket {\n"
"     background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 rgba(0, 255, 255, 200), \n"
"                                stop:0.5 rgba(200, 150, 255, 200), \n"
"                                stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid #0056b3;\n"
"    border-radius: 15px;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"/* Header \"Detail Tiket\" */\n"
"QLabel#label_header {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #007bff, stop:1 #0056b3);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    padding: 8px;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"}\n"
"\n"
"/* Garis pemisah di bawah header */\n"
"QFrame#frame_separator {\n"
"    background-color: #0056b3;\n"
"    min-height: 2px;\n"
"}\n"
"\n"
"/* Label untuk judul informasi */\n"
"QLabel#label_2,\n"
"QLabel#label_3,\n"
"QLabel#label_4,\n"
"QLabel#label_5,\n"
"QLabel#label_6,\n"
"QLabel#label_7,\n"
"QLabel#label_8,\n"
"QLabel#label_9,\n"
"QLabel#label_10,\n"
"QLabel#label_11,\n"
"QLabel#label_12,\n"
"QLabel#label_13 {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Label untuk isi informasi */\n"
"QLabel#label_namapenumpang,\n"
"QLabel#label_idkereta,\n"
"QLabel#label_namakereta,\n"
"QLabel#label_stasiunawal,\n"
"QLabel#label_stasiunakhir,\n"
"QLabel#label_tanggal,\n"
"QLabel#label_waktu,\n"
"QLabel#label_jenislayanan,\n"
"QLabel#label_idkursi,\n"
"QLabel#label_tarif,\n"
"QLabel#label_totaltarif,\n"
"QLabel#label_waktupemesanan {\n"
"    font-size: 10px;\n"
"    color: #555;\n"
"    background-color: #f0f3f5;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #ccc;\n"
"}\n"
"")
        self.frame_detail_tiket.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_detail_tiket.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_detail_tiket.setObjectName("frame_detail_tiket")
        self.label_header = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_header.setGeometry(QtCore.QRect(190, 20, 121, 31))
        self.label_header.setObjectName("label_header")
        self.label_2 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_3.setGeometry(QtCore.QRect(90, 100, 111, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_4.setGeometry(QtCore.QRect(90, 130, 111, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_5.setGeometry(QtCore.QRect(90, 160, 111, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_6.setGeometry(QtCore.QRect(90, 190, 111, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_7.setGeometry(QtCore.QRect(90, 220, 111, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_8.setGeometry(QtCore.QRect(90, 250, 111, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_9.setGeometry(QtCore.QRect(90, 280, 111, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_10.setGeometry(QtCore.QRect(90, 310, 111, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_11.setGeometry(QtCore.QRect(90, 340, 111, 21))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_13.setGeometry(QtCore.QRect(90, 370, 111, 21))
        self.label_13.setObjectName("label_13")
        self.label_namapenumpang = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_namapenumpang.setGeometry(QtCore.QRect(250, 70, 211, 21))
        self.label_namapenumpang.setObjectName("label_namapenumpang")
        self.label_idkereta = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_idkereta.setGeometry(QtCore.QRect(250, 100, 211, 21))
        self.label_idkereta.setObjectName("label_idkereta")
        self.label_namakereta = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_namakereta.setGeometry(QtCore.QRect(250, 130, 211, 21))
        self.label_namakereta.setObjectName("label_namakereta")
        self.label_stasiunawal = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_stasiunawal.setGeometry(QtCore.QRect(250, 160, 211, 21))
        self.label_stasiunawal.setObjectName("label_stasiunawal")
        self.label_stasiunakhir = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_stasiunakhir.setGeometry(QtCore.QRect(250, 190, 211, 21))
        self.label_stasiunakhir.setObjectName("label_stasiunakhir")
        self.label_tanggal = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_tanggal.setGeometry(QtCore.QRect(250, 220, 211, 21))
        self.label_tanggal.setObjectName("label_tanggal")
        self.label_waktu = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_waktu.setGeometry(QtCore.QRect(250, 250, 211, 21))
        self.label_waktu.setObjectName("label_waktu")
        self.label_jenislayanan = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_jenislayanan.setGeometry(QtCore.QRect(250, 280, 211, 21))
        self.label_jenislayanan.setObjectName("label_jenislayanan")
        self.label_idkursi = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_idkursi.setGeometry(QtCore.QRect(250, 310, 211, 21))
        self.label_idkursi.setObjectName("label_idkursi")
        self.label_tarif = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_tarif.setGeometry(QtCore.QRect(250, 340, 211, 21))
        self.label_tarif.setObjectName("label_tarif")
        self.label_waktupemesanan = QtWidgets.QLabel(self.frame_detail_tiket)
        self.label_waktupemesanan.setGeometry(QtCore.QRect(250, 370, 211, 21))
        self.label_waktupemesanan.setObjectName("label_waktupemesanan")
        self.button_kembali = QtWidgets.QPushButton(self.tiket_saya)
        self.button_kembali.setGeometry(QtCore.QRect(470, 690, 81, 31))
        self.button_kembali.setStyleSheet("QPushButton#button_kembali {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #ff4d4d, stop:1 #b30000);\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    border: 2px solid #b30000;\n"
"    transition: background 0.3s, transform 0.2s;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton#button_kembali:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #b30000, stop:1 #800000);\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"/* Saat ditekan */\n"
"QPushButton#button_kembali:pressed {\n"
"    background-color: #660000;\n"
"    border: 2px solid #4d0000;\n"
"    transform: scale(0.95);\n"
"}\n"
"")
        self.button_kembali.setObjectName("button_kembali")
        self.user.addWidget(self.tiket_saya)
        dashboard_detail_tiket.setCentralWidget(self.centralwidget)

        self.retranslateUi(dashboard_detail_tiket)
        self.user.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(dashboard_detail_tiket)

    def retranslateUi(self, dashboard_detail_tiket):
        _translate = QtCore.QCoreApplication.translate
        dashboard_detail_tiket.setWindowTitle(_translate("dashboard_detail_tiket", "Dashboard SAKAPEUNG"))
        self.home_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah dashboard user</span></p></body></html>"))
        self.home_title_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Dashboard User</span></p></body></html>"))
        self.pembelian_tiket_title_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Pembelian Tiket Kereta Api</span></p></body></html>"))
        self.pembelian_tiket_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu pembelian tiket</span></p></body></html>"))
        self.lihat_jadwal_kereta_title_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lihat Jadwal Kereta Api</span></p></body></html>"))
        self.lihat_jadwal_kereta_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu lihat jadwal kereta api</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.tiket_saya_tittle_user.setHtml(_translate("dashboard_detail_tiket", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Tiket Saya</span></p></body></html>"))
        self.label_header.setText(_translate("dashboard_detail_tiket", "Detail Tiket"))
        self.label_2.setText(_translate("dashboard_detail_tiket", "Nama Penumpang:"))
        self.label_3.setText(_translate("dashboard_detail_tiket", "ID Kereta:"))
        self.label_4.setText(_translate("dashboard_detail_tiket", "Nama kereta:"))
        self.label_5.setText(_translate("dashboard_detail_tiket", "Stasiun Awal:"))
        self.label_6.setText(_translate("dashboard_detail_tiket", "Stasiun Akhir:"))
        self.label_7.setText(_translate("dashboard_detail_tiket", "Tanggal:"))
        self.label_8.setText(_translate("dashboard_detail_tiket", "Waktu:"))
        self.label_9.setText(_translate("dashboard_detail_tiket", "Jenis Layanan:"))
        self.label_10.setText(_translate("dashboard_detail_tiket", "ID Kursi:"))
        self.label_11.setText(_translate("dashboard_detail_tiket", "Tarif:"))
        self.label_13.setText(_translate("dashboard_detail_tiket", "Waktu Pemesanan:"))
        self.label_namapenumpang.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_idkereta.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_namakereta.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_stasiunawal.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_stasiunakhir.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_tanggal.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_waktu.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_jenislayanan.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_idkursi.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_tarif.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.label_waktupemesanan.setText(_translate("dashboard_detail_tiket", "TextLabel"))
        self.button_kembali.setText(_translate("dashboard_detail_tiket", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard_detail_tiket = QtWidgets.QMainWindow()
    ui = Ui_dashboard_detail_tiket()
    ui.setupUi(dashboard_detail_tiket)
    dashboard_detail_tiket.show()
    sys.exit(app.exec_())
