# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_RekapKeuntungan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lihat_RekapKeuntungan(object):
    def setupUi(self, lihat_RekapKeuntungan):
        lihat_RekapKeuntungan.setObjectName("lihat_RekapKeuntungan")
        lihat_RekapKeuntungan.resize(1107, 879)
        lihat_RekapKeuntungan.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(lihat_RekapKeuntungan)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_utama)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1051, 781))
        self.stackedWidget.setStyleSheet("background : white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.admin = QtWidgets.QWidget()
        self.admin.setObjectName("admin")
        self.home_admin = QtWidgets.QTextEdit(self.admin)
        self.home_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.home_admin.setObjectName("home_admin")
        self.home_title_admin = QtWidgets.QTextBrowser(self.admin)
        self.home_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_admin.setObjectName("home_title_admin")
        self.stackedWidget.addWidget(self.admin)
        self.edit_jadwal_kereta = QtWidgets.QWidget()
        self.edit_jadwal_kereta.setObjectName("edit_jadwal_kereta")
        self.edit_jadwal_kereta_title_admin = QtWidgets.QTextBrowser(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.edit_jadwal_kereta_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.edit_jadwal_kereta_title_admin.setObjectName("edit_jadwal_kereta_title_admin")
        self.edit_jadwal_kereta_admin = QtWidgets.QTextEdit(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.edit_jadwal_kereta_admin.setObjectName("edit_jadwal_kereta_admin")
        self.stackedWidget.addWidget(self.edit_jadwal_kereta)
        self.lihat_rekap_keuntungan = QtWidgets.QWidget()
        self.lihat_rekap_keuntungan.setObjectName("lihat_rekap_keuntungan")
        self.lihat_rekap_keuntungan_title_admin = QtWidgets.QTextBrowser(self.lihat_rekap_keuntungan)
        self.lihat_rekap_keuntungan_title_admin.setGeometry(QtCore.QRect(0, 0, 1051, 111))
        self.lihat_rekap_keuntungan_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px;\n"
"")
        self.lihat_rekap_keuntungan_title_admin.setObjectName("lihat_rekap_keuntungan_title_admin")
        self.label = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label.setGeometry(QtCore.QRect(430, 160, 181, 41))
        self.label.setStyleSheet("/* Judul \"Lihat Rekap Keuntungan\" dengan background gradasi */\n"
"QLabel#label {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 12px;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    border: 2px solid #4a00e0;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_2.setGeometry(QtCore.QRect(250, 240, 131, 31))
        self.label_2.setStyleSheet("\n"
"\n"
"\n"
"/* Semua QLabel dalam statistik penjualan (statis dan dinamis) */\n"
"QLabel#label_2 {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_3.setGeometry(QtCore.QRect(250, 280, 131, 31))
        self.label_3.setStyleSheet("\n"
"\n"
"\n"
"/* Semua QLabel dalam statistik penjualan (statis dan dinamis) */\n"
"QLabel#label_3 {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_tiket_terjual = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_tiket_terjual.setGeometry(QtCore.QRect(390, 240, 141, 31))
        self.label_tiket_terjual.setStyleSheet("\n"
"\n"
"/* Semua QLabel dalam statistik penjualan (statis dan dinamis) */\n"
"QLabel#label_tiket_terjual{\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_tiket_terjual.setObjectName("label_tiket_terjual")
        self.label_total_pemasukan = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_total_pemasukan.setGeometry(QtCore.QRect(390, 280, 141, 31))
        self.label_total_pemasukan.setStyleSheet("\n"
"\n"
"\n"
"/* Semua QLabel dalam statistik penjualan (statis dan dinamis) */\n"
"QLabel#label_total_pemasukan {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_total_pemasukan.setObjectName("label_total_pemasukan")
        self.table_lihat_rekap_keuntungan = QtWidgets.QTableWidget(self.lihat_rekap_keuntungan)
        self.table_lihat_rekap_keuntungan.setGeometry(QtCore.QRect(250, 340, 531, 291))
        self.table_lihat_rekap_keuntungan.setStyleSheet("#table_lihat_rekap_keuntungan {\n"
"    background-color: #E3F2FD; /* Biru muda pastel */\n"
"    gridline-color: #BBDEFB; /* Garis antar sel */\n"
"    border: 2px solid #1976D2; /* Border biru sedang */\n"
"    font-size: 10px;\n"
"    color: #0D47A1; /* Warna teks biru tua */\n"
"    selection-background-color: #42A5F5; /* Biru lebih cerah saat dipilih */\n"
"    selection-color: white; /* Teks putih saat dipilih */\n"
"    alternate-background-color: #FFFFFF; /* Warna sel bergantian */\n"
"}\n"
"\n"
"/* Header tabel dengan gradasi */\n"
"QHeaderView::section {\n"
"    font-size: 10x;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 6px;\n"
"    border: 2px solid #4a00e0;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    border: 2px solid #4a00e0;\n"
"}\n"
"\n"
"/* Efek hover & selected */\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"/* Scrollbar Custom */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #E3F2FD;\n"
"    width: 10px;\n"
"    margin: 2px 0 2px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #1976D2;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"")
        self.table_lihat_rekap_keuntungan.setObjectName("table_lihat_rekap_keuntungan")
        self.table_lihat_rekap_keuntungan.setColumnCount(7)
        self.table_lihat_rekap_keuntungan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lihat_rekap_keuntungan.setHorizontalHeaderItem(6, item)
        self.button_kembali = QtWidgets.QPushButton(self.lihat_rekap_keuntungan)
        self.button_kembali.setGeometry(QtCore.QRect(370, 650, 91, 31))
        self.button_kembali.setStyleSheet("#button_kembali {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border: 2px solid #B71C1C;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF8A80, stop:1 #D32F2F); /* Lebih banyak merah terang */\n"
"}\n"
"\n"
"/* Efek hover */\n"
"#button_kembali:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF5252, stop:1 #B71C1C); /* Lebih merah saat hover */\n"
"    border: 2px solid #D32F2F;\n"
"}\n"
"\n"
"/* Efek tombol ditekan */\n"
"#button_kembali:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #F44336, stop:1 #9A0007); /* Merah lebih gelap saat ditekan */\n"
"    border: 2px solid #7F0000;\n"
"}\n"
"")
        self.button_kembali.setObjectName("button_kembali")
        self.button_lihat_detail_rekap = QtWidgets.QPushButton(self.lihat_rekap_keuntungan)
        self.button_lihat_detail_rekap.setGeometry(QtCore.QRect(260, 650, 101, 31))
        self.button_lihat_detail_rekap.setStyleSheet("QPushButton#button_lihat_detail_rekap {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #1976D2, stop:1 #64B5F6);\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #1565C0;\n"
"}\n"
"\n"
"/* Efek hover */\n"
"#button_lihat_detail_rekap:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #1565C0, stop:1 #42A5F5);\n"
"}\n"
"\n"
"/* Efek tombol ditekan */\n"
"#button_lihat_rekap:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #F44336, stop:1 #9A0007); /* Merah lebih gelap saat ditekan */\n"
"    border: 2px solid #7F0000;\n"
"}\n"
"")
        self.button_lihat_detail_rekap.setObjectName("button_lihat_detail_rekap")
        self.stackedWidget.addWidget(self.lihat_rekap_keuntungan)
        lihat_RekapKeuntungan.setCentralWidget(self.centralwidget)

        self.retranslateUi(lihat_RekapKeuntungan)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(lihat_RekapKeuntungan)

    def retranslateUi(self, lihat_RekapKeuntungan):
        _translate = QtCore.QCoreApplication.translate
        lihat_RekapKeuntungan.setWindowTitle(_translate("lihat_RekapKeuntungan", "Dashboard SAKAPEUNG"))
        self.home_admin.setHtml(_translate("lihat_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah dashbiard admin</span></p></body></html>"))
        self.home_title_admin.setHtml(_translate("lihat_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Dashboard Admin</span></p></body></html>"))
        self.edit_jadwal_kereta_title_admin.setHtml(_translate("lihat_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Edit Jadwal Kereta</span></p></body></html>"))
        self.edit_jadwal_kereta_admin.setHtml(_translate("lihat_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu edit jadwal kereta</span></p></body></html>"))
        self.lihat_rekap_keuntungan_title_admin.setHtml(_translate("lihat_RekapKeuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lihat Rekap Keuntungan</span></p></body></html>"))
        self.label.setText(_translate("lihat_RekapKeuntungan", "Lihat Rekap Keuntungan"))
        self.label_2.setText(_translate("lihat_RekapKeuntungan", "Total Tiket Terjual:"))
        self.label_3.setText(_translate("lihat_RekapKeuntungan", "Total Pemasukan: "))
        self.label_tiket_terjual.setText(_translate("lihat_RekapKeuntungan", "TextLabel"))
        self.label_total_pemasukan.setText(_translate("lihat_RekapKeuntungan", "TextLabel"))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(0)
        item.setText(_translate("lihat_RekapKeuntungan", "Nama "))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(1)
        item.setText(_translate("lihat_RekapKeuntungan", "Email"))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(2)
        item.setText(_translate("lihat_RekapKeuntungan", "Nama Kereta"))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(3)
        item.setText(_translate("lihat_RekapKeuntungan", "ID Kereta"))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(4)
        item.setText(_translate("lihat_RekapKeuntungan", "ID Kursi"))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(5)
        item.setText(_translate("lihat_RekapKeuntungan", "Total Tarif"))
        item = self.table_lihat_rekap_keuntungan.horizontalHeaderItem(6)
        item.setText(_translate("lihat_RekapKeuntungan", "Tanggal"))
        self.button_kembali.setText(_translate("lihat_RekapKeuntungan", "Kembali"))
        self.button_lihat_detail_rekap.setText(_translate("lihat_RekapKeuntungan", "Lihat Detail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lihat_RekapKeuntungan = QtWidgets.QMainWindow()
    ui = Ui_lihat_RekapKeuntungan()
    ui.setupUi(lihat_RekapKeuntungan)
    lihat_RekapKeuntungan.show()
    sys.exit(app.exec_())
