# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_grafik_keuntungan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lihat_grafik_keuntungan(object):
    def setupUi(self, lihat_grafik_keuntungan):
        lihat_grafik_keuntungan.setObjectName("lihat_grafik_keuntungan")
        lihat_grafik_keuntungan.resize(1107, 879)
        lihat_grafik_keuntungan.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(lihat_grafik_keuntungan)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_utama)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 1061, 781))
        self.stackedWidget.setStyleSheet("background : white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.admin = QtWidgets.QWidget()
        self.admin.setObjectName("admin")
        self.home_admin = QtWidgets.QTextEdit(self.admin)
        self.home_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.home_admin.setObjectName("home_admin")
        self.home_title_admin = QtWidgets.QTextBrowser(self.admin)
        self.home_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_admin.setObjectName("home_title_admin")
        self.stackedWidget.addWidget(self.admin)
        self.edit_jadwal_kereta = QtWidgets.QWidget()
        self.edit_jadwal_kereta.setObjectName("edit_jadwal_kereta")
        self.edit_jadwal_kereta_title_admin = QtWidgets.QTextBrowser(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_title_admin.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.edit_jadwal_kereta_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.edit_jadwal_kereta_title_admin.setObjectName("edit_jadwal_kereta_title_admin")
        self.edit_jadwal_kereta_admin = QtWidgets.QTextEdit(self.edit_jadwal_kereta)
        self.edit_jadwal_kereta_admin.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.edit_jadwal_kereta_admin.setObjectName("edit_jadwal_kereta_admin")
        self.stackedWidget.addWidget(self.edit_jadwal_kereta)
        self.lihat_rekap_keuntungan = QtWidgets.QWidget()
        self.lihat_rekap_keuntungan.setObjectName("lihat_rekap_keuntungan")
        self.lihat_rekap_keuntungan_title_admin = QtWidgets.QTextBrowser(self.lihat_rekap_keuntungan)
        self.lihat_rekap_keuntungan_title_admin.setGeometry(QtCore.QRect(-210, 0, 1301, 111))
        self.lihat_rekap_keuntungan_title_admin.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px;\n"
"")
        self.lihat_rekap_keuntungan_title_admin.setObjectName("lihat_rekap_keuntungan_title_admin")
        self.label = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label.setGeometry(QtCore.QRect(390, 140, 181, 51))
        self.label.setStyleSheet("/* Judul \"Lihat Rekap Keuntungan\" dengan background gradasi */\n"
"QLabel#label {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 12px;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    border: 2px solid #4a00e0;\n"
"}")
        self.label.setObjectName("label")
        self.combo_filter_rekap = QtWidgets.QComboBox(self.lihat_rekap_keuntungan)
        self.combo_filter_rekap.setGeometry(QtCore.QRect(120, 280, 71, 31))
        self.combo_filter_rekap.setStyleSheet("#combo_filter_rekap {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: #ffffff;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"    padding: 5px;\n"
"    border-radius: 6px;\n"
"    border: 2px solid #4a00e0;\n"
"    selection-background-color: #4a00e0;\n"
"}\n"
"\n"
"/* Dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #6a11cb;\n"
"    color: white;\n"
"    selection-background-color: #2575fc;\n"
"    border: 1px solid #4a00e0;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Saat hover */\n"
"#combo_filter_rekap:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #4a00e0, stop:1 #6a11cb);\n"
"}\n"
"\n"
"/* Saat ditekan */\n"
"#combo_filter_rekap:on {\n"
"    background: #4a00e0;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.combo_filter_rekap.setObjectName("combo_filter_rekap")
        self.combo_filter_rekap.addItem("")
        self.combo_filter_rekap.addItem("")
        self.combo_filter_rekap.addItem("")
        self.combo_filter_rekap.addItem("")
        self.label_2 = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_2.setGeometry(QtCore.QRect(120, 220, 121, 31))
        self.label_2.setStyleSheet("#label_2 {\n"
"     font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_total_pemasukan = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_total_pemasukan.setGeometry(QtCore.QRect(250, 220, 121, 31))
        self.label_total_pemasukan.setStyleSheet("#label_total_pemasukan {\n"
"     font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_total_pemasukan.setObjectName("label_total_pemasukan")
        self.label_persentase_perubahan = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_persentase_perubahan.setGeometry(QtCore.QRect(730, 220, 131, 31))
        self.label_persentase_perubahan.setStyleSheet("#label_persentase_perubahan {\n"
"     font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_persentase_perubahan.setObjectName("label_persentase_perubahan")
        self.label_3 = QtWidgets.QLabel(self.lihat_rekap_keuntungan)
        self.label_3.setGeometry(QtCore.QRect(570, 220, 151, 31))
        self.label_3.setStyleSheet("#label_3 {\n"
"     font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #a085ff, stop:1 #76baff);\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    border: 2px solid #76baff;\n"
"    box-shadow: 2px 4px 8px rgba(0, 0, 0, 0.1);\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.button_kembali = QtWidgets.QPushButton(self.lihat_rekap_keuntungan)
        self.button_kembali.setGeometry(QtCore.QRect(450, 610, 91, 31))
        self.button_kembali.setStyleSheet("#button_kembali {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border: 2px solid #B71C1C;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF8A80, stop:1 #D32F2F); /* Lebih banyak merah terang */\n"
"}\n"
"\n"
"/* Efek hover */\n"
"#button_kembali:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF5252, stop:1 #B71C1C); /* Lebih merah saat hover */\n"
"    border: 2px solid #D32F2F;\n"
"}\n"
"\n"
"/* Efek tombol ditekan */\n"
"#button_kembali:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #F44336, stop:1 #9A0007); /* Merah lebih gelap saat ditekan */\n"
"    border: 2px solid #7F0000;\n"
"}\n"
"")
        self.button_kembali.setObjectName("button_kembali")
        self.scrollArea_grafik = QtWidgets.QScrollArea(self.lihat_rekap_keuntungan)
        self.scrollArea_grafik.setGeometry(QtCore.QRect(200, 270, 651, 331))
        self.scrollArea_grafik.setWidgetResizable(True)
        self.scrollArea_grafik.setObjectName("scrollArea_grafik")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 651, 331))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.widget_grafik = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_grafik.setGeometry(QtCore.QRect(0, 10, 651, 311))
        self.widget_grafik.setStyleSheet("/* Style untuk widget grafik */\n"
"QWidget#widget_grafik {\n"
"    background-color: #E3F2FD; /* Biru muda pastel */\n"
"    border-radius: 10px;\n"
"    border: 2px solid #BBDEFB; /* Biru muda untuk garis agar serasi */\n"
"}\n"
"\n"
"/* Style untuk batang diagram */\n"
"QBarSet {\n"
"    color: white; /* Warna teks dalam batang */\n"
"}\n"
"\n"
"/* Style untuk warna batang diagram */\n"
"QBarSeries {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #6a11cb, stop:1 #2575fc);\n"
"}\n"
"/* Scroll area untuk grafik */\n"
"QScrollArea#widget_grafik {\n"
"    border: none;\n"
"    background: #E3F2FD; /* Warna latar belakang */\n"
"}\n"
"\n"
"/* Scrollbar Vertikal */\n"
"QScrollBar:vertical {\n"
"    background: #E3F2FD;\n"
"    width: 10px;\n"
"    margin: 2px 0 2px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #1976D2;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Scrollbar Horizontal */\n"
"QScrollBar:horizontal {\n"
"    background: #E3F2FD;\n"
"    height: 10px;\n"
"    margin: 0 2px 0 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #1976D2;\n"
"    min-width: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.widget_grafik.setObjectName("widget_grafik")
        self.scrollArea_grafik.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.lihat_rekap_keuntungan)
        lihat_grafik_keuntungan.setCentralWidget(self.centralwidget)

        self.retranslateUi(lihat_grafik_keuntungan)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(lihat_grafik_keuntungan)

    def retranslateUi(self, lihat_grafik_keuntungan):
        _translate = QtCore.QCoreApplication.translate
        lihat_grafik_keuntungan.setWindowTitle(_translate("lihat_grafik_keuntungan", "Dashboard SAKAPEUNG"))
        self.home_admin.setHtml(_translate("lihat_grafik_keuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah dashbiard admin</span></p></body></html>"))
        self.home_title_admin.setHtml(_translate("lihat_grafik_keuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Dashboard Admin</span></p></body></html>"))
        self.edit_jadwal_kereta_title_admin.setHtml(_translate("lihat_grafik_keuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Edit Jadwal Kereta</span></p></body></html>"))
        self.edit_jadwal_kereta_admin.setHtml(_translate("lihat_grafik_keuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu edit jadwal kereta</span></p></body></html>"))
        self.lihat_rekap_keuntungan_title_admin.setHtml(_translate("lihat_grafik_keuntungan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">    Lihat Rekap Keuntungan</span></p></body></html>"))
        self.label.setText(_translate("lihat_grafik_keuntungan", "Lihat Grafik Keuntungan"))
        self.combo_filter_rekap.setItemText(0, _translate("lihat_grafik_keuntungan", "Harian"))
        self.combo_filter_rekap.setItemText(1, _translate("lihat_grafik_keuntungan", "Mingguan"))
        self.combo_filter_rekap.setItemText(2, _translate("lihat_grafik_keuntungan", "Bulanan"))
        self.combo_filter_rekap.setItemText(3, _translate("lihat_grafik_keuntungan", "Tahunan"))
        self.label_2.setText(_translate("lihat_grafik_keuntungan", "Total Pemasukan:"))
        self.label_total_pemasukan.setText(_translate("lihat_grafik_keuntungan", "Text Label"))
        self.label_persentase_perubahan.setText(_translate("lihat_grafik_keuntungan", "Text Label"))
        self.label_3.setText(_translate("lihat_grafik_keuntungan", "Persentase Perubahan:"))
        self.button_kembali.setText(_translate("lihat_grafik_keuntungan", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lihat_grafik_keuntungan = QtWidgets.QMainWindow()
    ui = Ui_lihat_grafik_keuntungan()
    ui.setupUi(lihat_grafik_keuntungan)
    lihat_grafik_keuntungan.show()
    sys.exit(app.exec_())
