# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
Author: Mario Julius Christianto
NIM: 241524014
Kelas: 1A
Prodi: Sarjana Terapan Teknik Informatika
Jurusan: Teknik Komputer dan Informatika
Politeknik Negeri Bandung
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1280, 720)
        Login.setMinimumSize(QtCore.QSize(1280, 720))
        self.registrasi = QtWidgets.QWidget(Login)
        self.registrasi.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.registrasi.setMinimumSize(QtCore.QSize(1280, 720))
        self.registrasi.setObjectName("registrasi")
        self.label = QtWidgets.QLabel(self.registrasi)
        self.label.setGeometry(QtCore.QRect(-4, 2, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/registration_page.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.email_input = QtWidgets.QLineEdit(self.registrasi)
        self.email_input.setGeometry(QtCore.QRect(590, 179, 311, 61))
        self.email_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.email_input.setObjectName("email_input")
        self.password_input = QtWidgets.QLineEdit(self.registrasi)
        self.password_input.setGeometry(QtCore.QRect(920, 180, 311, 61))
        self.password_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.password_input.setObjectName("password_input")
        self.nama_input = QtWidgets.QLineEdit(self.registrasi)
        self.nama_input.setGeometry(QtCore.QRect(590, 280, 641, 61))
        self.nama_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.nama_input.setObjectName("nama_input")
        self.nomor_telepon_input = QtWidgets.QLineEdit(self.registrasi)
        self.nomor_telepon_input.setGeometry(QtCore.QRect(590, 370, 311, 61))
        self.nomor_telepon_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.nomor_telepon_input.setObjectName("nomor_telepon_input")
        self.alamat_input = QtWidgets.QLineEdit(self.registrasi)
        self.alamat_input.setGeometry(QtCore.QRect(920, 370, 311, 61))
        self.alamat_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.alamat_input.setObjectName("alamat_input")
        self.nomor_rekening_input = QtWidgets.QLineEdit(self.registrasi)
        self.nomor_rekening_input.setGeometry(QtCore.QRect(590, 470, 201, 61))
        self.nomor_rekening_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.nomor_rekening_input.setObjectName("nomor_rekening_input")
        self.pin_input = QtWidgets.QLineEdit(self.registrasi)
        self.pin_input.setGeometry(QtCore.QRect(800, 470, 211, 61))
        self.pin_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.pin_input.setObjectName("pin_input")
        self.saldo_input = QtWidgets.QLineEdit(self.registrasi)
        self.saldo_input.setGeometry(QtCore.QRect(1020, 470, 211, 61))
        self.saldo_input.setStyleSheet("border: 2px solid #B0C4DE; /* Warna biru muda */\n"
"        border-radius: 15px; /* Sudut melengkung */\n"
"        padding: 5px;\n"
"        background: white;\n"
"font-family: \"Montserrat\";\n"
"        font-size: 20px;\n"
"        color: #333;")
        self.saldo_input.setObjectName("saldo_input")
        self.submit_data = QtWidgets.QPushButton(self.registrasi)
        self.submit_data.setGeometry(QtCore.QRect(590, 542, 641, 71))
        self.submit_data.setStyleSheet("background-color: transparent;\n"
"        color: white; /* Warna teks putih */\n"
"        border-radius: 20px; /* Membuat sudut melengkung */\n"
"        font-size: 16px; /* Ukuran teks */\n"
"        font-weight: bold; /* Membuat teks tebal */\n"
"        padding: 10px 40px; /* Padding untuk ukuran tombol */\n"
"font-family: \"{Montserrat}\"; /* Gunakan font Montserrat */\n"
"        font-size: 16px; /* Ukuran teks */\n"
"        font-weight: bold;")
        self.submit_data.setText("")
        self.submit_data.setObjectName("submit_data")
        self.login = QtWidgets.QPushButton(self.registrasi)
        self.login.setGeometry(QtCore.QRect(760, 620, 71, 21))
        self.login.setStyleSheet("background-color: transparent;\n"
"        color: white; /* Warna teks putih */\n"
"        border-radius: 20px; /* Membuat sudut melengkung */\n"
"        font-size: 16px; /* Ukuran teks */\n"
"        font-weight: bold; /* Membuat teks tebal */\n"
"        padding: 10px 40px; /* Padding untuk ukuran tombol */\n"
"font-family: \"{Montserrat}\"; /* Gunakan font Montserrat */\n"
"        font-size: 16px; /* Ukuran teks */\n"
"        font-weight: bold;")
        self.login.setText("")
        self.login.setObjectName("login")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Register()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
