# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tiket_show_box(object):
    def setupUi(self, tiket_show_box):
        tiket_show_box.setObjectName("tiket_show_box")
        tiket_show_box.resize(1280, 766)
        tiket_show_box.setMaximumSize(QtCore.QSize(1280, 766))
        tiket_show_box.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.kereta_box = QtWidgets.QFrame(tiket_show_box)
        self.kereta_box.setGeometry(QtCore.QRect(120, 30, 1041, 710))
        self.kereta_box.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */\n"
"")
        self.kereta_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kereta_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kereta_box.setObjectName("kereta_box")
        self.tiket_box = QtWidgets.QWidget(self.kereta_box)
        self.tiket_box.setGeometry(QtCore.QRect(30, 110, 991, 511))
        self.tiket_box.setStyleSheet("background : white;")
        self.tiket_box.setObjectName("tiket_box")
        self.table_pesan_tiket = QtWidgets.QTableWidget(self.tiket_box)
        self.table_pesan_tiket.setGeometry(QtCore.QRect(30, 50, 941, 441))
        self.table_pesan_tiket.setStyleSheet("QTableWidget {\n"
"    background-color: white; /* Warna ungu muda untuk latar tabel */\n"
"    border-radius: 10px;\n"
"    gridline-color: rgb(202, 202, 202); /* Warna garis antar sel */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color:rgb(202, 202, 202);\n"
"    color: black;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    border-bottom: 0px solid #004085; /* Garis bawah tegas */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: 1px solid rgb(202, 202, 202); /* Warna border antar sel */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(202, 202, 202); /* Warna ungu terang untuk item terpilih */\n"
"    color: black;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(255, 255, 255) ; /* Warna sudut kiri atas tabel */\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.table_pesan_tiket.setObjectName("table_pesan_tiket")
        self.table_pesan_tiket.setColumnCount(6)
        self.table_pesan_tiket.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pesan_tiket.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pesan_tiket.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pesan_tiket.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pesan_tiket.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pesan_tiket.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_pesan_tiket.setItem(0, 5, item)
        self.table_pesan_tiket.horizontalHeader().setDefaultSectionSize(150)
        self.table_pesan_tiket.horizontalHeader().setStretchLastSection(True)
        self.button_keluar = QtWidgets.QPushButton(self.kereta_box)
        self.button_keluar.setGeometry(QtCore.QRect(30, 640, 991, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_keluar.setFont(font)
        self.button_keluar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(44, 181, 255);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-family: \'Montserrat\';\n"
"    font-weight: bold;\n"
"    font-size: 14pt; \n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.button_keluar.setObjectName("button_keluar")
        self.label = QtWidgets.QLabel(self.kereta_box)
        self.label.setGeometry(QtCore.QRect(30, 15, 991, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(tiket_show_box)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1280, 766))
        self.label_5.setMaximumSize(QtCore.QSize(1280, 766))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("ui/3.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.kereta_box.raise_()

        self.retranslateUi(tiket_show_box)
        QtCore.QMetaObject.connectSlotsByName(tiket_show_box)

    def retranslateUi(self, tiket_show_box):
        _translate = QtCore.QCoreApplication.translate
        tiket_show_box.setWindowTitle(_translate("tiket_show_box", "Dialog"))
        item = self.table_pesan_tiket.horizontalHeaderItem(0)
        item.setText(_translate("tiket_show_box", "Nama Kereta "))
        item = self.table_pesan_tiket.horizontalHeaderItem(1)
        item.setText(_translate("tiket_show_box", "Stasiun Asal "))
        item = self.table_pesan_tiket.horizontalHeaderItem(2)
        item.setText(_translate("tiket_show_box", "Stasiun Tujuan"))
        item = self.table_pesan_tiket.horizontalHeaderItem(3)
        item.setText(_translate("tiket_show_box", "Waktu Berangkat"))
        item = self.table_pesan_tiket.horizontalHeaderItem(4)
        item.setText(_translate("tiket_show_box", "Waktu Tiba"))
        item = self.table_pesan_tiket.horizontalHeaderItem(5)
        item.setText(_translate("tiket_show_box", "Harga Tiket"))
        __sortingEnabled = self.table_pesan_tiket.isSortingEnabled()
        self.table_pesan_tiket.setSortingEnabled(False)
        self.table_pesan_tiket.setSortingEnabled(__sortingEnabled)
        self.button_keluar.setText(_translate("tiket_show_box", "KELUAR"))
        self.label.setText(_translate("tiket_show_box", "     PILIH TIKET ANDA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tiket_show_box = QtWidgets.QDialog()
    ui = Ui_tiket_show_box()
    ui.setupUi(tiket_show_box)
    tiket_show_box.show()
    sys.exit(app.exec_())
