# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TICKETBOOKING(object):
    def setupUi(self, TICKETBOOKING):
        TICKETBOOKING.setObjectName("TICKETBOOKING")
        TICKETBOOKING.resize(1280, 766)
        TICKETBOOKING.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.box_Booking = QtWidgets.QFrame(TICKETBOOKING)
        self.box_Booking.setGeometry(QtCore.QRect(130, 20, 891, 731))
        self.box_Booking.setMaximumSize(QtCore.QSize(1280, 766))
        self.box_Booking.setStyleSheet("background-color: rgba(255, 255, 255, 150); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */\n"
"")
        self.box_Booking.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_Booking.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_Booking.setObjectName("box_Booking")
        self.TicketBooking = QtWidgets.QWidget(self.box_Booking)
        self.TicketBooking.setGeometry(QtCore.QRect(40, 50, 821, 651))
        self.TicketBooking.setStyleSheet("background : white;")
        self.TicketBooking.setObjectName("TicketBooking")
        self.button_cari = QtWidgets.QPushButton(self.TicketBooking)
        self.button_cari.setGeometry(QtCore.QRect(110, 490, 601, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_cari.setFont(font)
        self.button_cari.setStyleSheet("QPushButton {\n"
"    background-color: rgb(44, 181, 255);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-family: \'Montserrat\';\n"
"    font-weight: bold;\n"
"    font-size: 14pt; \n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.button_cari.setObjectName("button_cari")
        self.button_keluar = QtWidgets.QPushButton(self.TicketBooking)
        self.button_keluar.setGeometry(QtCore.QRect(110, 540, 601, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_keluar.setFont(font)
        self.button_keluar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(44, 181, 255);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-family: \'Montserrat\';\n"
"    font-weight: bold;\n"
"    font-size: 14pt; \n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.button_keluar.setObjectName("button_keluar")
        self.widget = QtWidgets.QWidget(self.TicketBooking)
        self.widget.setGeometry(QtCore.QRect(110, 110, 601, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_asal = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_asal.setFont(font)
        self.label_asal.setObjectName("label_asal")
        self.horizontalLayout.addWidget(self.label_asal)
        self.pushButton_Swap = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Swap.setFont(font)
        self.pushButton_Swap.setObjectName("pushButton_Swap")
        self.horizontalLayout.addWidget(self.pushButton_Swap)
        self.combo_asal = QtWidgets.QComboBox(self.widget)
        self.combo_asal.setObjectName("combo_asal")
        self.horizontalLayout.addWidget(self.combo_asal)
        self.widget_2 = QtWidgets.QWidget(self.TicketBooking)
        self.widget_2.setGeometry(QtCore.QRect(110, 190, 601, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Tujuan = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Tujuan.setFont(font)
        self.label_Tujuan.setObjectName("label_Tujuan")
        self.horizontalLayout_2.addWidget(self.label_Tujuan)
        self.combo_tujuan = QtWidgets.QComboBox(self.widget_2)
        self.combo_tujuan.setObjectName("combo_tujuan")
        self.horizontalLayout_2.addWidget(self.combo_tujuan)
        self.widget_3 = QtWidgets.QWidget(self.TicketBooking)
        self.widget_3.setGeometry(QtCore.QRect(110, 270, 601, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selected_date = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selected_date.setFont(font)
        self.selected_date.setObjectName("selected_date")
        self.horizontalLayout_3.addWidget(self.selected_date)
        self.button_tanggal = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_tanggal.setFont(font)
        self.button_tanggal.setObjectName("button_tanggal")
        self.horizontalLayout_3.addWidget(self.button_tanggal)
        self.widget_4 = QtWidgets.QWidget(self.TicketBooking)
        self.widget_4.setGeometry(QtCore.QRect(110, 350, 601, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Tanggal_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Tanggal_2.setFont(font)
        self.label_Tanggal_2.setObjectName("label_Tanggal_2")
        self.horizontalLayout_4.addWidget(self.label_Tanggal_2)
        self.pushButton_Tanggal_2 = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Tanggal_2.setFont(font)
        self.pushButton_Tanggal_2.setText("")
        self.pushButton_Tanggal_2.setObjectName("pushButton_Tanggal_2")
        self.horizontalLayout_4.addWidget(self.pushButton_Tanggal_2)
        self.combo_layanan = QtWidgets.QComboBox(self.widget_4)
        self.combo_layanan.setObjectName("combo_layanan")
        self.horizontalLayout_4.addWidget(self.combo_layanan)
        self.label = QtWidgets.QLabel(self.TicketBooking)
        self.label.setGeometry(QtCore.QRect(280, 40, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: \'Montserrat\';\n"
"font-size: 20pt; /* atau sesuaikan ukuran */   \n"
"color: #333333;  /* warna teks opsional */   \n"
"background-color: transparent; /* background opsional */\n"
"    border: none;\n"
"font-weight: bold;\n"
"\n"
" background-color: rgba(255, 255, 255, 0); /* semi-transparan putih */\n"
"    color: #000000;  /* teks tetap hitam/solid */\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(TICKETBOOKING)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1280, 766))
        self.label_4.setMaximumSize(QtCore.QSize(1280, 766))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui/3.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.box_Booking.raise_()

        self.retranslateUi(TICKETBOOKING)
        QtCore.QMetaObject.connectSlotsByName(TICKETBOOKING)

    def retranslateUi(self, TICKETBOOKING):
        _translate = QtCore.QCoreApplication.translate
        TICKETBOOKING.setWindowTitle(_translate("TICKETBOOKING", "Dialog"))
        self.button_cari.setText(_translate("TICKETBOOKING", "CARI TIKET "))
        self.button_keluar.setText(_translate("TICKETBOOKING", "KELUAR"))
        self.label_asal.setText(_translate("TICKETBOOKING", "Stasiun asal : "))
        self.pushButton_Swap.setText(_translate("TICKETBOOKING", "⇄"))
        self.label_Tujuan.setText(_translate("TICKETBOOKING", "Stasiun Tujuan : "))
        self.selected_date.setText(_translate("TICKETBOOKING", "Tanggal Keberangkatan "))
        self.button_tanggal.setText(_translate("TICKETBOOKING", "Masukan  Tanggal "))
        self.label_Tanggal_2.setText(_translate("TICKETBOOKING", "Jenis Layanan : "))
        self.label.setText(_translate("TICKETBOOKING", "TIKET KERETA "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TICKETBOOKING = QtWidgets.QDialog()
    ui = Ui_TICKETBOOKING()
    ui.setupUi(TICKETBOOKING)
    TICKETBOOKING.show()
    sys.exit(app.exec_())
