"""
Nama: Adi Rafi Chaerufarizki
NIM: 241524001
Kelas: 1A
Prodi: Sarjana Terapan Teknik Informatika
Jurusan: Teknik Komputer dan Informatika
Politeknik Negeri Bandung
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tiket_saya.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard_tiket_saya(object):
    def setupUi(self, dashboard_tiket_saya):
        dashboard_tiket_saya.setObjectName("dashboard_tiket_saya")
        dashboard_tiket_saya.resize(1107, 879)
        dashboard_tiket_saya.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.centralwidget = QtWidgets.QWidget(dashboard_tiket_saya)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_utama = QtWidgets.QFrame(self.centralwidget)
        self.frame_utama.setGeometry(QtCore.QRect(30, 30, 1051, 781))
        self.frame_utama.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */")
        self.frame_utama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_utama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_utama.setObjectName("frame_utama")
        self.user = QtWidgets.QStackedWidget(self.frame_utama)
        self.user.setGeometry(QtCore.QRect(0, -10, 1061, 781))
        self.user.setStyleSheet("background : white;")
        self.user.setFrameShape(QtWidgets.QFrame.Box)
        self.user.setFrameShadow(QtWidgets.QFrame.Plain)
        self.user.setObjectName("user")
        self.user_dashboard = QtWidgets.QWidget()
        self.user_dashboard.setObjectName("user_dashboard")
        self.home_user = QtWidgets.QTextEdit(self.user_dashboard)
        self.home_user.setGeometry(QtCore.QRect(0, 120, 791, 651))
        self.home_user.setObjectName("home_user")
        self.home_title_user = QtWidgets.QTextBrowser(self.user_dashboard)
        self.home_title_user.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.home_title_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.home_title_user.setObjectName("home_title_user")
        self.user.addWidget(self.user_dashboard)
        self.pembelian_tiket = QtWidgets.QWidget()
        self.pembelian_tiket.setObjectName("pembelian_tiket")
        self.pembelian_tiket_title_user = QtWidgets.QTextBrowser(self.pembelian_tiket)
        self.pembelian_tiket_title_user.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.pembelian_tiket_title_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; \n"
"")
        self.pembelian_tiket_title_user.setObjectName("pembelian_tiket_title_user")
        self.pembelian_tiket_user = QtWidgets.QTextEdit(self.pembelian_tiket)
        self.pembelian_tiket_user.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.pembelian_tiket_user.setObjectName("pembelian_tiket_user")
        self.user.addWidget(self.pembelian_tiket)
        self.lihat_jadwal_kereta = QtWidgets.QWidget()
        self.lihat_jadwal_kereta.setObjectName("lihat_jadwal_kereta")
        self.lihat_jadwal_kereta_title_user = QtWidgets.QTextBrowser(self.lihat_jadwal_kereta)
        self.lihat_jadwal_kereta_title_user.setGeometry(QtCore.QRect(0, 0, 811, 111))
        self.lihat_jadwal_kereta_title_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; ")
        self.lihat_jadwal_kereta_title_user.setObjectName("lihat_jadwal_kereta_title_user")
        self.lihat_jadwal_kereta_user = QtWidgets.QTextEdit(self.lihat_jadwal_kereta)
        self.lihat_jadwal_kereta_user.setGeometry(QtCore.QRect(10, 120, 791, 651))
        self.lihat_jadwal_kereta_user.setObjectName("lihat_jadwal_kereta_user")
        self.user.addWidget(self.lihat_jadwal_kereta)
        self.tiket_saya = QtWidgets.QWidget()
        self.tiket_saya.setObjectName("tiket_saya")
        self.tiket_saya_tittle_user = QtWidgets.QTextBrowser(self.tiket_saya)
        self.tiket_saya_tittle_user.setGeometry(QtCore.QRect(-80, 10, 1131, 111))
        self.tiket_saya_tittle_user.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"border-radius: 0px; ")
        self.tiket_saya_tittle_user.setObjectName("tiket_saya_tittle_user")
        self.button_detail = QtWidgets.QPushButton(self.tiket_saya)
        self.button_detail.setEnabled(True)
        self.button_detail.setGeometry(QtCore.QRect(350, 690, 101, 31))
        self.button_detail.setStyleSheet("QPushButton#button_detail {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #007bff, stop:1 #0056b3);\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    border: 2px solid #0056b3;\n"
"    transition: background 0.3s, transform 0.2s;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton#button_detail:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #0056b3, stop:1 #004494);\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"/* Saat ditekan */\n"
"QPushButton#button_detail:pressed {\n"
"    background-color: #003366;\n"
"    border: 2px solid #002244;\n"
"    transform: scale(0.95);\n"
"}\n"
"")
        self.button_detail.setObjectName("button_detail")
        self.table_tiket_saya = QtWidgets.QTableWidget(self.tiket_saya)
        self.table_tiket_saya.setGeometry(QtCore.QRect(180, 210, 661, 341))
        self.table_tiket_saya.setStyleSheet("/* ==================== QTableWidget ==================== */\n"
"QTableWidget {\n"
"    background-color: #ffffff; /* Background putih */\n"
"    border: 2px solid #007bff; /* Border biru */\n"
"    border-radius: 8px; /* Sudut membulat */\n"
"    gridline-color: #d1d1d1; /* Warna garis antar sel */\n"
"    font-size: 14px;\n"
"    selection-background-color: #007bff; /* Warna saat dipilih */\n"
"    selection-color: white; /* Warna teks saat dipilih */\n"
"    alternate-background-color: #f2f2f2; /* Warna baris selang-seling */\n"
"}\n"
"\n"
"/* ==================== Header (Kolom Atas) ==================== */\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #007bff, stop:1 #0056b3);\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    border-bottom: 3px solid #004085; /* Garis bawah tegas */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* ==================== Baris (Row) ==================== */\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #d1d1d1;\n"
"}\n"
"\n"
"/* Alternatif warna tiap baris */\n"
"QTableWidget::item:alternate {\n"
"    background-color: #f2f2f2; /* Abu muda */\n"
"}\n"
"\n"
"/* Hover efek saat kursor di atas baris */\n"
"QTableWidget::item:hover {\n"
"    background-color: #cce5ff;\n"
"    color: black;\n"
"    transition: background-color 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* ==================== Scrollbar (Gulir) ==================== */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #007bff;\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* ==================== Sudut (Corner) ==================== */\n"
"QTableCornerButton::section {\n"
"    background-color: #007bff;\n"
"    border: none;\n"
"}\n"
"QTableWidget {\n"
"    gridline-color: #AAAAAA; /* Warna garis grid */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border-bottom: 1px solid #CCCCCC; /* Garis horizontal */\n"
"    border-right: 1px solid #CCCCCC; /* Garis vertikal */\n"
"}\n"
"\n"
"")
        self.table_tiket_saya.setObjectName("table_tiket_saya")
        self.table_tiket_saya.setColumnCount(5)
        self.table_tiket_saya.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_tiket_saya.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tiket_saya.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tiket_saya.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tiket_saya.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tiket_saya.setHorizontalHeaderItem(4, item)
        self.table_tiket_saya.horizontalHeader().setDefaultSectionSize(120)
        self.table_tiket_saya.horizontalHeader().setStretchLastSection(True)
        self.lineEdit = QtWidgets.QLineEdit(self.tiket_saya)
        self.lineEdit.setGeometry(QtCore.QRect(430, 610, 111, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #4A90E2;  /* Warna biru elegan */\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #333;  /* Warna teks gelap agar mudah dibaca */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #7B68EE;  /* Warna ungu lembut saat fokus */\n"
"    background-color: #F0F8FF;  /* Biru muda untuk efek fokus */\n"
"}\n"
"")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.tiket_saya)
        self.textEdit.setGeometry(QtCore.QRect(330, 580, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.button_kembali = QtWidgets.QPushButton(self.tiket_saya)
        self.button_kembali.setGeometry(QtCore.QRect(550, 690, 91, 31))
        self.button_kembali.setStyleSheet("QPushButton#button_kembali {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #ff4d4d, stop:1 #b30000);\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    border: 2px solid #b30000;\n"
"    transition: background 0.3s, transform 0.2s;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton#button_kembali:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #b30000, stop:1 #800000);\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"/* Saat ditekan */\n"
"QPushButton#button_kembali:pressed {\n"
"    background-color: #660000;\n"
"    border: 2px solid #4d0000;\n"
"    transform: scale(0.95);\n"
"}\n"
"")
        self.button_kembali.setObjectName("button_kembali")
        self.label_header = QtWidgets.QLabel(self.tiket_saya)
        self.label_header.setGeometry(QtCore.QRect(430, 150, 111, 41))
        self.label_header.setStyleSheet("/* Header \"Detail Tiket\" */\n"
"QLabel#label_header {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #007bff, stop:1 #0056b3);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    padding: 8px;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"}")
        self.label_header.setObjectName("label_header")
        self.tiket_saya_tittle_user.raise_()
        self.button_detail.raise_()
        self.table_tiket_saya.raise_()
        self.textEdit.raise_()
        self.lineEdit.raise_()
        self.button_kembali.raise_()
        self.label_header.raise_()
        self.user.addWidget(self.tiket_saya)
        dashboard_tiket_saya.setCentralWidget(self.centralwidget)

        self.retranslateUi(dashboard_tiket_saya)
        self.user.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(dashboard_tiket_saya)

    def retranslateUi(self, dashboard_tiket_saya):
        _translate = QtCore.QCoreApplication.translate
        dashboard_tiket_saya.setWindowTitle(_translate("dashboard_tiket_saya", "Dashboard SAKAPEUNG"))
        self.home_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.home_title_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt;\"><br /></p>\n"
"<p align=\"center\" dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Tiket Saya</span></p></body></html>"))
        self.pembelian_tiket_title_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Pembelian Tiket Kereta Api</span></p></body></html>"))
        self.pembelian_tiket_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu pembelian tiket</span></p></body></html>"))
        self.lihat_jadwal_kereta_title_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lihat Jadwal Kereta Api</span></p></body></html>"))
        self.lihat_jadwal_kereta_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Ini adalah menu lihat jadwal kereta api</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.tiket_saya_tittle_user.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Tiket Saya</span></p></body></html>"))
        self.button_detail.setText(_translate("dashboard_tiket_saya", "Lihat Detail"))
        item = self.table_tiket_saya.horizontalHeaderItem(0)
        item.setText(_translate("dashboard_tiket_saya", "ID Kereta"))
        item = self.table_tiket_saya.horizontalHeaderItem(1)
        item.setText(_translate("dashboard_tiket_saya", "Nama Kereta"))
        item = self.table_tiket_saya.horizontalHeaderItem(2)
        item.setText(_translate("dashboard_tiket_saya", "Stasiun Awal"))
        item = self.table_tiket_saya.horizontalHeaderItem(3)
        item.setText(_translate("dashboard_tiket_saya", "Stasiun Akhir"))
        item = self.table_tiket_saya.horizontalHeaderItem(4)
        item.setText(_translate("dashboard_tiket_saya", "Tanggal"))
        self.textEdit.setHtml(_translate("dashboard_tiket_saya", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Masukkan ID Kereta</span></p></body></html>"))
        self.button_kembali.setText(_translate("dashboard_tiket_saya", "Kembali"))
        self.label_header.setText(_translate("dashboard_tiket_saya", "Tiket Saya"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard_tiket_saya = QtWidgets.QMainWindow()
    ui = Ui_dashboard_tiket_saya()
    ui.setupUi(dashboard_tiket_saya)
    dashboard_tiket_saya.show()
    sys.exit(app.exec_())
