# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaksi_pembayaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transaksi_pembayaran(object):
    def setupUi(self, transaksi_pembayaran):
        transaksi_pembayaran.setObjectName("transaksi_pembayaran")
        transaksi_pembayaran.resize(1147, 865)
        transaksi_pembayaran.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6a11cb, stop:1 #2575fc);\n"
"")
        self.kereta_box = QtWidgets.QFrame(transaksi_pembayaran)
        self.kereta_box.setGeometry(QtCore.QRect(50, 40, 1041, 771))
        self.kereta_box.setStyleSheet("background-color: rgba(255, 255, 255, 180); /* Transparansi */\n"
"border-radius: 15px; /* Membuat sudut melengkung */\n"
"")
        self.kereta_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kereta_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kereta_box.setObjectName("kereta_box")
        self.kursi_kereta_box = QtWidgets.QWidget(self.kereta_box)
        self.kursi_kereta_box.setGeometry(QtCore.QRect(30, 330, 971, 311))
        self.kursi_kereta_box.setStyleSheet("background : rgb(158, 213, 255);")
        self.kursi_kereta_box.setObjectName("kursi_kereta_box")
        self.groupBox = QtWidgets.QGroupBox(self.kursi_kereta_box)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 921, 241))
        self.groupBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 25px;  /* Lebar kotak */\n"
"    height: 25px; /* Tinggi kotak */\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_saldo = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_saldo.setGeometry(QtCore.QRect(70, 60, 801, 51))
        self.groupBox_saldo.setStyleSheet("background : white;\n"
"")
        self.groupBox_saldo.setTitle("")
        self.groupBox_saldo.setObjectName("groupBox_saldo")
        self.label_saldouser = QtWidgets.QLabel(self.groupBox_saldo)
        self.label_saldouser.setGeometry(QtCore.QRect(20, 0, 251, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_saldouser.setFont(font)
        self.label_saldouser.setStyleSheet("background : white;")
        self.label_saldouser.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saldouser.setObjectName("label_saldouser")
        self.label_saldo = QtWidgets.QLabel(self.groupBox_saldo)
        self.label_saldo.setGeometry(QtCore.QRect(550, 0, 191, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_saldo.setFont(font)
        self.label_saldo.setStyleSheet("background : white;")
        self.label_saldo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saldo.setObjectName("label_saldo")
        self.label_inputrekening = QtWidgets.QLabel(self.groupBox)
        self.label_inputrekening.setGeometry(QtCore.QRect(70, 120, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_inputrekening.setFont(font)
        self.label_inputrekening.setStyleSheet("background : white;")
        self.label_inputrekening.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_inputrekening.setObjectName("label_inputrekening")
        self.label_harga = QtWidgets.QLabel(self.groupBox)
        self.label_harga.setGeometry(QtCore.QRect(630, 130, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_harga.setFont(font)
        self.label_harga.setStyleSheet("background : white;")
        self.label_harga.setText("")
        self.label_harga.setAlignment(QtCore.Qt.AlignCenter)
        self.label_harga.setObjectName("label_harga")
        self.line_pinNorek = QtWidgets.QLineEdit(self.groupBox)
        self.line_pinNorek.setGeometry(QtCore.QRect(600, 120, 231, 41))
        self.line_pinNorek.setStyleSheet("    border: none;\n"
"    border-bottom: 2px solid black;\n"
"    border-radius: 0px;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    background: transparent;")
        self.line_pinNorek.setText("")
        self.line_pinNorek.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_pinNorek.setObjectName("line_pinNorek")
        self.label_5 = QtWidgets.QLabel(self.kursi_kereta_box)
        self.label_5.setGeometry(QtCore.QRect(270, 30, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.textBrowser_data_ = QtWidgets.QTextBrowser(self.kereta_box)
        self.textBrowser_data_.setGeometry(QtCore.QRect(30, 10, 971, 301))
        self.textBrowser_data_.setStyleSheet("background : rgb(158, 213, 255);")
        self.textBrowser_data_.setObjectName("textBrowser_data_")
        self.button_keluar = QtWidgets.QPushButton(self.kereta_box)
        self.button_keluar.setGeometry(QtCore.QRect(30, 700, 971, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_keluar.setFont(font)
        self.button_keluar.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.button_keluar.setObjectName("button_keluar")
        self.button_bayar = QtWidgets.QPushButton(self.kereta_box)
        self.button_bayar.setGeometry(QtCore.QRect(30, 650, 971, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_bayar.setFont(font)
        self.button_bayar.setStyleSheet("QPushButton {\n"
"    background-color: #007BFF;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}\n"
"")
        self.button_bayar.setObjectName("button_bayar")
        self.label_waktu_ticket = QtWidgets.QLabel(self.kereta_box)
        self.label_waktu_ticket.setGeometry(QtCore.QRect(130, 90, 431, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_waktu_ticket.setFont(font)
        self.label_waktu_ticket.setAlignment(QtCore.Qt.AlignCenter)
        self.label_waktu_ticket.setObjectName("label_waktu_ticket")
        self.label_nama_kereta = QtWidgets.QLabel(self.kereta_box)
        self.label_nama_kereta.setGeometry(QtCore.QRect(130, 220, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nama_kereta.setFont(font)
        self.label_nama_kereta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nama_kereta.setObjectName("label_nama_kereta")
        self.label_layanan = QtWidgets.QLabel(self.kereta_box)
        self.label_layanan.setGeometry(QtCore.QRect(330, 220, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_layanan.setFont(font)
        self.label_layanan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_layanan.setObjectName("label_layanan")
        self.label_penumpang = QtWidgets.QLabel(self.kereta_box)
        self.label_penumpang.setGeometry(QtCore.QRect(520, 220, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_penumpang.setFont(font)
        self.label_penumpang.setAlignment(QtCore.Qt.AlignCenter)
        self.label_penumpang.setObjectName("label_penumpang")
        self.label_container_asaltujan = QtWidgets.QLabel(self.kereta_box)
        self.label_container_asaltujan.setGeometry(QtCore.QRect(130, 130, 771, 81))
        self.label_container_asaltujan.setText("")
        self.label_container_asaltujan.setObjectName("label_container_asaltujan")
        self.label_asal = QtWidgets.QLabel(self.kereta_box)
        self.label_asal.setGeometry(QtCore.QRect(170, 140, 221, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_asal.setFont(font)
        self.label_asal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asal.setObjectName("label_asal")
        self.label_tujuan = QtWidgets.QLabel(self.kereta_box)
        self.label_tujuan.setGeometry(QtCore.QRect(640, 140, 221, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_tujuan.setFont(font)
        self.label_tujuan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tujuan.setObjectName("label_tujuan")
        self.label_harga_2 = QtWidgets.QLabel(self.kereta_box)
        self.label_harga_2.setGeometry(QtCore.QRect(130, 260, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_harga_2.setFont(font)
        self.label_harga_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_harga_2.setObjectName("label_harga_2")
        self.label_kursi = QtWidgets.QLabel(self.kereta_box)
        self.label_kursi.setGeometry(QtCore.QRect(330, 260, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_kursi.setFont(font)
        self.label_kursi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kursi.setObjectName("label_kursi")
        self.label_3 = QtWidgets.QLabel(self.kereta_box)
        self.label_3.setGeometry(QtCore.QRect(470, 140, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(transaksi_pembayaran)
        QtCore.QMetaObject.connectSlotsByName(transaksi_pembayaran)

    def retranslateUi(self, transaksi_pembayaran):
        _translate = QtCore.QCoreApplication.translate
        transaksi_pembayaran.setWindowTitle(_translate("transaksi_pembayaran", "Dialog"))
        self.label_saldouser.setText(_translate("transaksi_pembayaran", "SALDO ANDA "))
        self.label_saldo.setText(_translate("transaksi_pembayaran", "SALDO"))
        self.label_inputrekening.setText(_translate("transaksi_pembayaran", "          MASUKAN PIN REKENING ANDA "))
        self.line_pinNorek.setPlaceholderText(_translate("transaksi_pembayaran", "masukkan PIN anda .... "))
        self.label_5.setText(_translate("transaksi_pembayaran", "TRANSAKSI PEMBAYARAN "))
        self.textBrowser_data_.setHtml(_translate("transaksi_pembayaran", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">PESAN TIKET </span></p></body></html>"))
        self.button_keluar.setText(_translate("transaksi_pembayaran", "KELUAR"))
        self.button_bayar.setText(_translate("transaksi_pembayaran", "BAYAR"))
        self.label_waktu_ticket.setText(_translate("transaksi_pembayaran", "TANGGAL KEBERANGKATAN DAN WAKTU KERETA "))
        self.label_nama_kereta.setText(_translate("transaksi_pembayaran", "NAMA KERETA"))
        self.label_layanan.setText(_translate("transaksi_pembayaran", "JENIS LAYANAN"))
        self.label_penumpang.setText(_translate("transaksi_pembayaran", "1 PENUMPANG "))
        self.label_asal.setText(_translate("transaksi_pembayaran", "ASAL"))
        self.label_tujuan.setText(_translate("transaksi_pembayaran", "TUJUAN"))
        self.label_harga_2.setText(_translate("transaksi_pembayaran", "HARGA KERETA"))
        self.label_kursi.setText(_translate("transaksi_pembayaran", "ID KURSI"))
        self.label_3.setText(_translate("transaksi_pembayaran", "→ "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transaksi_pembayaran = QtWidgets.QDialog()
    ui = Ui_transaksi_pembayaran()
    ui.setupUi(transaksi_pembayaran)
    transaksi_pembayaran.show()
    sys.exit(app.exec_())
