# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
Author: Mario Julius Christianto
NIM: 241524014
Kelas: 1A
Prodi: Sarjana Terapan Teknik Informatika
Jurusan: Teknik Komputer dan Informatika
Politeknik Negeri Bandung
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(1280, 718)
        Welcome.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(Welcome)
        self.centralwidget.setObjectName("centralwidget")
        self.central_widget = QtWidgets.QWidget(self.centralwidget)
        self.central_widget.setGeometry(QtCore.QRect(0, 0, 1271, 681))
        self.central_widget.setMinimumSize(QtCore.QSize(16, 9))
        self.central_widget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.central_widget.setStyleSheet("background :rgb(148, 148, 148)\n"
"")
        self.central_widget.setObjectName("central_widget")
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1271, 681))
        self.label.setMinimumSize(QtCore.QSize(16, 9))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\loading_screen.png"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.tombol_enter_untuk_lanjut = QtWidgets.QPushButton(self.central_widget)
        self.tombol_enter_untuk_lanjut.setGeometry(QtCore.QRect(444, 540, 371, 23))
        self.tombol_enter_untuk_lanjut.setStyleSheet("background : transparent;")
        self.tombol_enter_untuk_lanjut.setText("")
        self.tombol_enter_untuk_lanjut.setObjectName("tombol_enter_untuk_lanjut")
        Welcome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Welcome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        Welcome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Welcome)
        self.statusbar.setObjectName("statusbar")
        Welcome.setStatusBar(self.statusbar)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Welcome = QtWidgets.QMainWindow()
    ui = Ui_Welcome()
    ui.setupUi(Welcome)
    Welcome.show()
    sys.exit(app.exec_())
